import type { Props as TrekkerReviewCard } from "../ui/TrekkerReviewCard.astro";

export const trekkerReviewExample: TrekkerReviewCard[] = [
  {
    photo: "https://randomuser.me/api/portraits/women/65.jpg",
    country: "Argentina",
    date: "2025-06-21",
    message: "Una experiencia inolvidable, los paisajes fueron hermosos.",
    name: "Lucía Martínez",
    score: 5,
    title: "Simplemente mágico",
  },
  {
    photo: "https://randomuser.me/api/portraits/men/12.jpg",
    country: "Chile",
    date: "2025-06-20",
    message: "Buen viaje, aunque esperaba un poco más de organización.",
    name: "Carlos Rivas",
    score: 3,
    title: "Interesante pero mejorable",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/33.jpg",
    country: "Colombia",
    date: "2025-06-22",
    message: "Todo fue perfecto, desde el inicio hasta el final.",
    name: "Ana Gómez",
    score: 5,
    title: "Recomendado al 100%",
  },
  {
    photo: "https://randomuser.me/api/portraits/men/48.jpg",
    country: "México",
    date: "2025-06-19",
    message: "La comida y los guías fueron geniales, volvería sin dudar.",
    name: "Javier López",
    score: 4,
    title: "Muy buena experiencia",
  },
  {
    photo: "https://randomuser.me/api/portraits/men/35.jpg",
    country: "Uruguay",
    date: "2025-06-18",
    message: "No me gustó el alojamiento, pero los paisajes compensaron.",
    name: "Martín Pereyra",
    score: 2,
    title: "Con altibajos",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/41.jpg",
    country: "Bolivia",
    date: "2025-06-23",
    message: "Muy divertido, ideal para desconectarse de todo.",
    name: "Sofía Arce",
    score: 4,
    title: "Relax total",
  },
  {
    photo: "https://randomuser.me/api/portraits/men/21.jpg",
    country: "Ecuador",
    date: "2025-06-23",
    message: "Demasiado calor para mi gusto, pero fue una buena aventura.",
    name: "Diego Torres",
    score: 3,
    title: "Un viaje diferente",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/58.jpg",
    country: "Perú",
    date: "2025-06-23",
    message: "La mejor semana del año sin duda alguna.",
    name: "Valeria Córdova",
    score: 5,
    title: "Vacaciones soñadas",
  },
];
